### ISSUE TITLE
Reduce request and response package size

### ISSUE THREAD

**Issue by fdietze** [renesca/renesca#11]
- http compression
- less http headers?
- compact print json

**Comment by snordquist** [comment]
http compression: if the db is running on the same machine, we should evaluate if there is a performance boost. If the db is not running on localhost, this should help.

less http headers: I dont think that this is noticable

compact print json: the amount of transfered data is reduced by some bytes, but I think the perfomance depends on the implementation of the used json frameworks

**Comment by fdietze** [comment]
All points need to be tested.

**Comment by fdietze** [comment]
Usage of the neo4j binary bolt protocol will probably solve this.
