### ISSUE TITLE
Why should I use Renesca or Renesca Magic rather than the Scala ones?

### ISSUE THREAD

**Issue by PhilAndrew** [renesca/renesca#47]
https://github.com/FaKod/neo4j-scala

https://github.com/AnormCypher/AnormCypher

https://github.com/outworkers/reactiveneo

Gremlin with NEO4J https://github.com/mpollmeier/gremlin-scala

https://github.com/thinkaurelius/neo4j-gremlin-plugin

https://github.com/AnormCypher/AnormCypher

Can someone please tell me why this one rather than other ones? I don't need a full comparison of all of these but need to have some reasons why to use this one.

**Comment by fdietze** [comment]
This really depends on what you want to do. One thing that's special for renesca is the fact that query results are actually graph datastructures. You can modify these graphs and send the changes back to the database. All over the REST API.

renesca-magic is for more serious type-safe data-modeling on top of this renesca graph structure.

Feel free to ask any more questions.
