### ISSUE TITLE
Code assumes neo4j server is accessable at localhost:7474

### ISSUE THREAD

**Issue by sheldon-white** [renesca/renesca#48]
In RestService:

def rollbackTransaction(id: TransactionId) {
    // we don't wait for a response here
    pipeline(HttpRequest(DELETE, s"http://localhost:7474/db/data/transaction/$id"))
}

That won't work in most real-world cases.

**Comment by cornerman** [comment]
Good catch, totally overlooked that one. Thanks for reporting!
